name    = "my-music-stdio"
restart = "on-failure"

[processes.main]
command = "/Users/huanghao/workspace/my-music-stdio/.venv/bin/python -m uvicorn src.server:app --port ${PORT:-3050} --reload"
port    = 3050
